#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/join_table_general

csvjoin -c file <(filter_file uniform_byte) <(filter_file uniform_token) <(filter_file polya_token) <(filter_file polya_stoken_uniform_token) <(filter_file polya_stoken_uniform_byte) | \
  csvcut -c 1,2,3,4,5,6,8,9,10,11,12,14,15,16,17,18,20,21,22,23,24,26,27,28,29,30 | \
  csvsort -c file > $OUTPUT
