#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/join_table_general

csvjoin -c file <(filter_file uniform_byte) <(filter_file uniform_token) <(filter_file polya_token) | \
  csvcut -c 1,2,3,4,5,6,8,9,10,11,12,14,15,16,17,18 | \
  csvsort -c file > $OUTPUT
